### ISSUE TITLE
Need Cargo.lock

### ISSUE THREAD

**Issue by wz14** [BitVM/BitVM#113]
Wonder if we should add `Cargo.lock` to repo.  Fail to build many times, because of forgetting to run `Cargo update`.

**Comment by lucidLuckylee** [comment]
I'm not really in favor of this. Any reasons why we should do that beyond forgetting to run `cargo update`?

**Comment by wz14** [comment]
I just think BitVM as a community repo needs to provide some deterministic verification on everyone's computer, following this practice: https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control

**Comment by lucidLuckylee** [comment]
Added `Cargo.lock` in [be4674b](https://github.com/BitVM/BitVM/commit/be4674b0cff2ac7e18cab8024223d8f8303ae4d9)
