### ISSUE TITLE
Can't use latest `rust-bitcoin`

### ISSUE THREAD

**Issue by tcharding** [BitVM/BitVM#23]
I believe you guys can't use the latest `rust-bitcoin`. If you want, I can try help push that forward by:

- Upstreaming anything you need from Steven's fork
- Doing the upgrade

Please either close this and tell me to go away or throw some notes up for me and I'll get to it.

We'd like to use BitVM to help test release candidates of `rust-bitcoin`.

**Comment by lucidLuckylee** [comment]
Yes that is correct and thank you for having a look into that. Getting rid of the extra depdency would be great!

The dependency on Steven's fork comes from the [script interpreter](https://github.com/BitVM/rust-bitcoin-scriptexec) but I don't have an overview what exactly we need from Steven's fork other than what the compiler complains is missing when switching to bitcoin 0.31.1.

**Comment by RobinLinus** [comment]
Great, thank you @tcharding !!

**Comment by lucidLuckylee** [comment]
Closed with #158.
