### ISSUE TITLE
Why not compare the instruction directly when Paul and Vicky find the disputed one?

### ISSUE THREAD

**Issue by JiangXb-son** [BitVM/BitVM#3]
<img width="968" alt="image" src="https://github.com/BitVM/BitVM/assets/61689830/b83e116f-d6eb-4f3d-adea-bec327153127">

For example, when Paul and Vicky find the disputed instruction is :

Add. add_A, add_B, add_C, val_A, val_B, val_C

Both Paul and Vicky could reveal this instruction and push these data on Bitcoin to execute Punish Equivocation.

Why do there need additional challenges for each element?

**Comment by RobinLinus** [comment]
yes, you're right! we updated the graph and changed the code accordingly 
https://github.com/BitVM/BitVM/blob/main/docs/bitVM_graph_v2.svg
