### ISSUE TITLE
Automatic code optimizations

### ISSUE THREAD

**Issue by RobinLinus** [BitVM/BitVM#42]
In our [JavaScript prototype](https://github.com/BitVM/bitvm-js/blob/main/scripts/compile.js#L25) we had automatic code optimizations for simple patters, e.g. replace `1 OP_ROLL` with `OP_SWAP`. 

We should implement that again.

**Comment by weikengchen** [comment]
Maybe we can start with a warning system---that is, let the compiler complain about redundant codes.

This allows us to detect that. Let me try to implement that...

**Comment by weikengchen** [comment]
Having the compiler complain is easier in that the script can stay Vec<u8>

**Comment by lucidLuckylee** [comment]
I added automatic code optimizations to the macro here: https://github.com/BitVM/rust-bitcoin-script/tree/optimal_opcodes in a way that we do not have to call any other function.
However it affects performance. BitVM test_scalar_mul takes about twice the time than without substitution.
