### ISSUE TITLE
Enable larger inputs for Blake3

### ISSUE THREAD

**Issue by RobinLinus** [BitVM/BitVM#45]
Currently, we support only one 40-byte or 64-byte inputs. We need an implementation for 512-byte and 1024-byte inputs.

**Comment by weikengchen** [comment]
This issue is partly solved except that for 1024-byte inputs, the message would need to be stored in a more compact manner.
This could be implemented by adding a bit decomposition and composition process.

**Comment by RobinLinus** [comment]
Thanks @weikengchen!
