### ISSUE TITLE
Uncompress blake3 inputs on-demand

### ISSUE THREAD

**Issue by lucidLuckylee** [BitVM/BitVM#90]
The current version of the blake3 hash function can at most hash 640 inputs. Several chunk scripts already use more than that even with 29bit limbs. For the hash function these 29bit stack entries would have to be serialized to bytes roughly quadrupling the number of stack elements meant to be hashed. This approach seems infeasible.

Therefore, we aim to store all u32 in a single stack element either by:
a) Geting rid of the `u8_xor_table` and facilitate u32_xor with another (yet to be found) approach that works directly on 32 bit stack elements.
b) Serializing 32 bit stack elements to bytes on demand ONLY in the hash function as it seems to be the only script that requires bytes (in particular because of the xor operation).

TODOs in case of b):
- [x] Change `blake_3_var_length` to serialize message (input) values to bytes on-demand only when they are used in the compression function
- [ ] Change `blake3_var_length` to keep the inputs on the stack
- [ ] Implement u32 operations (u32_add, u32_sub, etc.) on 32 bit stack elements using Bitcoins arithmetic opcodes in combination with e.g. OP_SIZE to handle overflow (note that Bitcoins arithmetic opcodes are signed and we need unsigned operations)
- [ ] Optional: Explore 32bit limbs for Field elements (as this might not be worth)

These change should allow us to hash ~636~ 256 32 (or 29) bit stack elements with `blake3_var_length`

**Comment by lucidLuckylee** [comment]
Update as @wz14 pointed out that the script size when hashing 636 32bit stack elements will be infeasibly large.

Hashing the maximum of 1024 bytes with blake3 results in 1.6MB of script so we can at most hash 256 32bit stack elements.

**Comment by Cyimon** [comment]
"The current version of the blake3 hash function can at most hash 640 inputs. "

Can you explain more about how the "640 inputs" comes?

**Comment by lucidLuckylee** [comment]
Think I just ran a test and over 640 inputs used more than 1000 stack elements.
The math should roughly check out: 1000 (stack limit) - 256 (lookup table size) - 64 (state size) = 680 inputs at most. I guess the other 40 stack elements are used up in the rotations and xor operations

**Comment by lucidLuckylee** [comment]
Just reran the test and 640 inputs use at max 968 stack elements

**Comment by Cyimon** [comment]
"Change blake_3_var_length to serialize message (input) values to bytes on-demand only when they are used in the compression function"

I tried to implement this optimization and found that it doesn't work now:
There are 7 rounds in a compress function;
Each round has 8 "G" functions;
Each "G" has 4 XOR operators;

If we serialize the input(32bits) into bytes before each XOR operation, let's name it as "uncompress" :
It needs to 2 "uncompress" for 2 inputs

So for each "G", there are 2 * 4 = 8 "uncompress" operations
For each round: there are 8 * 8 = 64 "uncompress" operations
For each compress: there are 64 * 7 = 448

Each uncompress script size is 553 bytes

For 1 compress script size:  448 *553 = 247,744 bytes

Current blake3 script is ~0.1M
The new version is ~0.4M

It still has some room to reduce, I just give some data I got first

**Comment by lucidLuckylee** [comment]
I haven't checked your calculations but we have to uncompress the limbs that are supposed to be hashed either way to serialize them into bytes. Instead of doing that for every limb before the hash function we want to do it in the hash function only when that part of the message is required and keep it in that uncompressed part until we are done with it.

**Comment by lucidLuckylee** [comment]
I moved the remaining hashing property to its own issue #108
