### ISSUE TITLE
Feat: Specify hint placeholders for a `Script`

### ISSUE THREAD

**Issue by lucidLuckylee** [BitVM/BitVM#96]
To split the script into chunks we can't push all hints at the start of the script. Instead, we should only provide them as inputs to the chunk that actually requires them. To achieve that we can use a new pseudo opcode `OP_HINT` that is replaced by e.g. `OP_RESERVED1` in the script macro and later substituted by the stack analyzer to `OP_ROLL` the correct stack depth.
That way the stack analyzer will know that an input is supposed to be accessed and we can still catch errors where a script tries to access values not on the stack.
See: https://github.com/BitVM/rust-bitcoin-script/issues/1

**Comment by whbjzzwjxq** [comment]
May I have a question here: what does `hint` mean in the context? It looks like a way to mark the location of splitting. I tried to understand from the code snippet but only got this:

```rust
pub enum Hint {
    Fq(ark_bn254::Fq),
}

impl Hint {
    pub fn push(&self) -> Script {
        match self {
            Hint::Fq(fq) => script! {
                { fq_push_not_montgomery(*fq) }
            },
        }
    }
}
```

**Comment by lucidLuckylee** [comment]
Not necessary for the manual layout
